# Generated by Django 5.1.7 on 2025-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('revenue', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('employees', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
